Repository k-bialucha/business-assistant-mobile-app, pull requests merged in 2020-05, with the labels that each got.

#12 [docs] README file
  .env.example
  README.md
Labels: documentation

#11 [feature] Sign in with facebook
  package-lock.json
  package.json
  redux/auth/actions.test.ts
  redux/auth/actions.ts
  redux/auth/saga.ts
  redux/auth/types.ts
  screens/AuthScreen.tsx
  screens/SettingsScreen.tsx
  screens/SignupScreen.styled.ts
  utils/apiCalls/authorization.ts
  utils/firebase.ts
Labels: dependencies, enhancement, environment settings

#13 [feature] Firebase integration - saga tests
  .env.example
  .gitignore
  __mocks__/env.ts
  __mocks__/expo-facebook.ts
  babel.config.js
  env.example.ts
  package-lock.json
  package.json
  redux/auth/__snapshots__/saga.test.ts.snap
  redux/auth/saga.test.ts
  redux/auth/saga.ts
  utils/apiCalls/authorization.ts
  utils/firebase.ts
Labels: enhancement

#14 [feature] Signin with facebook saga tests fix
  redux/auth/saga.test.ts
Labels: bug

#15 [feature] Authorization with google
  env.example.ts
  package-lock.json
  package.json
  redux/auth/__snapshots__/saga.test.ts.snap
  redux/auth/actions.test.ts
  redux/auth/actions.ts
  redux/auth/saga.test.ts
  redux/auth/saga.ts
  redux/auth/types.ts
  screens/AuthScreen.tsx
Labels: dependencies, enhancement, environment settings

#18 [feature] Auto login
  navigation/NavContainer.tsx
  redux/auth/__snapshots__/saga.test.ts.snap
  redux/auth/actions.test.ts
  redux/auth/actions.ts
  redux/auth/reducer.test.ts
  redux/auth/reducer.ts
  redux/auth/saga.test.ts
  redux/auth/saga.ts
  redux/auth/types.ts
  screens/StartupScreen.style.ts
  screens/StartupScreen.test.tsx
  screens/StartupScreen.tsx
  screens/__snapshots__/SignupScreen.test.tsx.snap
  screens/__snapshots__/StartupScreen.test.tsx.snap
Labels: enhancement
