Repository k-bialucha/business-assistant-mobile-app, pull requests merged in 2021-01, with the labels that each got.

#32 [feature] Basic calculation
  .eslintrc.js
  package-lock.json
  package.json
  src/calculation/CostElement.test.ts
  src/calculation/CostElement.ts
  src/calculation/SaleElement.test.ts
  src/calculation/SaleElement.ts
  src/calculation/calculate.test.ts
  src/calculation/calculate.ts
  src/calculation/constants.ts
  src/calculation/roundSum.test.ts
  src/calculation/roundSum.ts
  src/components/form/TextField.tsx
  src/models/Sale.ts
  src/navigation/NavContainer.tsx
  src/redux/auth/actions.test.ts
  src/redux/auth/reducer.test.ts
  src/screens/UserSettingsScreen/UserSettingsScreen.tsx
Labels: enhancement, environment settings

#34 [feature] Setting app language basing on the region
  app.json
  package-lock.json
  package.json
  src/components/form/TextField.tsx
  src/screens/ResetPasswordScreen/ResetPasswordScreen.spec.tsx
  src/utils/i18n.ts
  src/utils/translations/pl.ts
Labels: dependencies, enhancement, environment settings

#33 [Feature] Translations constants
  .prettierrc
  app.json
  package-lock.json
  package.json
  src/components/form/TextField.tsx
  src/hooks/useAppTranslation.ts
  src/screens/AuthScreen/AuthScreen.tsx
  src/screens/CostsListScreen/CostsListScreen.tsx
  src/screens/LoginScreen/LoginScreen.tsx
  src/screens/ResetPasswordScreen/ResetPasswordScreen.spec.tsx
  src/screens/ResetPasswordScreen/ResetPasswordScreen.tsx
  src/screens/SalesListScreen/SalesListScreen.tsx
  src/screens/SettingsScreen/SettingsScreen.tsx
  src/screens/SettingsScreen/__snapshots__/SettingsScreen.test.tsx.snap
  src/screens/SignupScreen/SignupScreen.tsx
  src/screens/UserSettingsScreen/UserSettingsScreen.tsx
  src/utils/i18n.ts
  src/utils/translations/en.ts
  src/utils/translations/pl.ts
  src/utils/translations/types.ts
Labels: dependencies, enhancement, help wanted, tests
